server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carclub1?serverTimezone=UTC
    username: root
    password: 123456
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 12345678

  aop:
    proxy-target-class: true
    auto: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    path: D:/网络开发/files/